/**
 * Core types for the download system
 * This file contains all shared types used across different download services
 */

// ═══════════════════════════════════════════════════════════════════════════════
// VIDEO TYPES
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Represents a video format option available for download
 */
export interface VideoFormat {
  formatId: string;
  extension: string;
  resolution: string | null;
  quality: string;
  filesize: number | null;
  filesizeApprox: number | null;
  fps: number | null;
  vcodec: string | null;
  acodec: string | null;
  hasVideo: boolean;
  hasAudio: boolean;
  tbr: number | null; // Total bitrate
  protocol?: string | null; // Download protocol (e.g., "https", "m3u8_native" for HLS)
}

/**
 * Represents a refined quality option for the UI
 */
export interface QualityOption {
  key: string;
  label: string;
  quality: string;
  resolution: string;
  totalSize: number | null;
  videoFormat?: VideoFormat;
  audioFormat?: VideoFormat;
}

/**
 * Thumbnail information for a video
 */
export interface Thumbnail {
  url: string;
  width?: number;
  height?: number;
  resolution?: string;
}

/**
 * Subtitle/Caption track information
 */
export interface SubtitleTrack {
  language: string;
  languageCode: string;
  url: string;
  ext: string;
  isAutoGenerated: boolean;
}

/**
 * Complete video information extracted from URL
 */
export interface VideoInfo {
  id: string;
  title: string;
  description: string | null;
  duration: number | null; // In seconds
  durationString: string | null;
  uploader: string | null;
  uploaderUrl: string | null;
  uploadDate: string | null;
  viewCount: number | null;
  likeCount: number | null;
  thumbnail: string | null;
  thumbnails: Thumbnail[];
  formats: VideoFormat[];
  subtitles: Record<string, SubtitleTrack[]>;
  webpage_url: string;
  extractor: string;
  extractorKey: string;
  isLive: boolean;
  isPlaylist: boolean;
  qualityOptions?: QualityOption[];
  playlist?: PlaylistInfo;
}

/**
 * Playlist information
 */
export interface PlaylistInfo {
  id: string;
  title: string;
  description: string | null;
  uploader: string | null;
  uploaderUrl: string | null;
  thumbnail: string | null;
  videoCount: number;
  videos: PlaylistVideoEntry[];
}

/**
 * Video entry in a playlist
 */
export interface PlaylistVideoEntry {
  id: string;
  title: string;
  duration: number | null;
  thumbnail: string | null;
  url: string;
  index: number;
}

// ═══════════════════════════════════════════════════════════════════════════════
// DOWNLOAD TYPES
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Download status enumeration
 */
export enum DownloadStatus {
  PENDING = "pending",
  EXTRACTING = "extracting",
  DOWNLOADING = "downloading",
  MERGING = "merging",
  CONVERTING = "converting",
  COMPLETED = "completed",
  PAUSED = "paused",
  FAILED = "failed",
  CANCELLED = "cancelled",
}

/**
 * URL Detection modes
 */
export type DetectionMode = "auto" | "direct" | "video";

/**
 * Download quality presets
 */
export enum DownloadQuality {
  BEST = "best",
  BEST_VIDEO = "bestvideo+bestaudio",
  QUALITY_4K = "2160p",
  QUALITY_1440P = "1440p",
  QUALITY_1080P = "1080p",
  QUALITY_720P = "720p",
  QUALITY_480P = "480p",
  QUALITY_360P = "360p",
  AUDIO_ONLY = "bestaudio",
}

/**
 * Options for downloading a video
 */
export interface DownloadOptions {
  url: string;
  outputPath: string;
  filename?: string;
  quality?: DownloadQuality | string;
  format?: string; // Specific format ID or format selector
  audioOnly?: boolean;
  subtitles?: {
    download: boolean;
    languages?: string[]; // e.g., ['en', 'ar']
    embedInVideo?: boolean;
  };
  thumbnail?: {
    download: boolean;
    embedInVideo?: boolean;
  };
  metadata?: {
    embedInVideo?: boolean;
  };
  rateLimit?: string; // e.g., '1M' for 1MB/s limit
  proxy?: string;
  cookies?: string; // Path to cookies file
  verbose?: boolean; // Enable verbose logging for debugging (e.g., YouTube empty file errors)
}

/**
 * Download progress information
 */
export interface DownloadProgress {
  downloadId: string;
  status: DownloadStatus;
  progress: number; // 0-100
  downloadedBytes: number;
  totalBytes: number | null;
  speed: number | null; // Bytes per second
  speedString: string | null; // Human-readable speed
  eta: number | null; // Seconds remaining
  etaString: string | null; // Human-readable ETA
  filename: string | null;
  currentFragment?: number;
  totalFragments?: number;
}

/**
 * Complete download item/task
 */
export interface DownloadItem {
  id: string;
  url: string;
  videoInfo: VideoInfo | null;
  options: DownloadOptions;
  status: DownloadStatus;
  progress: DownloadProgress;
  outputPath: string;
  filename: string | null;
  createdAt: Date;
  startedAt: Date | null;
  completedAt: Date | null;
  error: string | null;
  retryCount: number;
}

/**
 * Download queue configuration
 */
export interface QueueConfig {
  maxConcurrentDownloads: number;
  autoRetry: boolean;
  maxRetries: number;
  retryDelay: number; // Milliseconds
}

// ═══════════════════════════════════════════════════════════════════════════════
// PLATFORM TYPES
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Supported platform information
 */
export interface PlatformInfo {
  name: string;
  icon: string;
  domains: string[];
  supportsPlaylist: boolean;
  supportsSubtitles: boolean;
  supportsQualitySelection: boolean;
}

/**
 * Common platforms configuration
 */
export const SUPPORTED_PLATFORMS: Record<string, PlatformInfo> = {
  youtube: {
    name: "YouTube",
    icon: "youtube",
    domains: ["youtube.com", "youtu.be", "youtube-nocookie.com"],
    supportsPlaylist: true,
    supportsSubtitles: true,
    supportsQualitySelection: true,
  },
  tiktok: {
    name: "TikTok",
    icon: "tiktok",
    domains: ["tiktok.com", "vm.tiktok.com"],
    supportsPlaylist: false,
    supportsSubtitles: false,
    supportsQualitySelection: true,
  },
  instagram: {
    name: "Instagram",
    icon: "instagram",
    domains: ["instagram.com", "instagr.am"],
    supportsPlaylist: false,
    supportsSubtitles: false,
    supportsQualitySelection: true,
  },
  twitter: {
    name: "Twitter/X",
    icon: "twitter",
    domains: ["twitter.com", "x.com"],
    supportsPlaylist: false,
    supportsSubtitles: false,
    supportsQualitySelection: true,
  },
  facebook: {
    name: "Facebook",
    icon: "facebook",
    domains: ["facebook.com", "fb.watch", "fb.com"],
    supportsPlaylist: false,
    supportsSubtitles: true,
    supportsQualitySelection: true,
  },
  vimeo: {
    name: "Vimeo",
    icon: "vimeo",
    domains: ["vimeo.com", "player.vimeo.com"],
    supportsPlaylist: true,
    supportsSubtitles: true,
    supportsQualitySelection: true,
  },
  dailymotion: {
    name: "Dailymotion",
    icon: "dailymotion",
    domains: ["dailymotion.com", "dai.ly"],
    supportsPlaylist: true,
    supportsSubtitles: true,
    supportsQualitySelection: true,
  },
  twitch: {
    name: "Twitch",
    icon: "twitch",
    domains: ["twitch.tv", "clips.twitch.tv"],
    supportsPlaylist: false,
    supportsSubtitles: false,
    supportsQualitySelection: true,
  },
};

// ═══════════════════════════════════════════════════════════════════════════════
// IPC CHANNEL TYPES
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * IPC channels for download communication
 */
export const DownloadIpcChannels = {
  // Requests from Renderer to Main
  EXTRACT_VIDEO_INFO: "download:extract-video-info",
  START_DOWNLOAD: "download:start",
  START_DIRECT_DOWNLOAD: "download:start-direct",
  DETECT_LINK_TYPE: "download:detect-link-type",
  PAUSE_DOWNLOAD: "download:pause",
  RESUME_DOWNLOAD: "download:resume",
  CANCEL_DOWNLOAD: "download:cancel",
  GET_DOWNLOAD_STATUS: "download:get-status",
  GET_ALL_DOWNLOADS: "download:get-all",
  CLEAR_COMPLETED: "download:clear-completed",

  // Events from Main to Renderer
  DOWNLOAD_PROGRESS: "download:progress",
  DOWNLOAD_COMPLETE: "download:complete",
  DOWNLOAD_ERROR: "download:error",
  DOWNLOAD_STATUS_CHANGED: "download:status-changed",
  DOWNLOAD_REMOVED: "download:removed",
  VIDEO_INFO_EXTRACTED: "download:video-info-extracted",
} as const;

/**
 * API Response wrapper
 */
export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  error?: string;
  message?: string;
}
